### ISSUE TITLE
ggcor 无法安装了

### ISSUE THREAD

**Issue by mj163163** [zlabx/Microbiome#1]
ggcor没法安装了，GitHub账号好像都没有了

**Comment by zjdevo** [comment]
你好，鉴于这个情况，zlabx暂时提供备用源https://github.com/zlabx/ggcor，请使用该源安装，ggcor版权归属为houyunhuang,本实验室仅提供应急源，不享有ggcor任何权益。谢谢哈~如有疑问，请到本仓库ggcor处留言，谢谢

**Comment by mj163163** [comment]
多谢！

**Comment by Longchunyan7788** [comment]
请问还有别的备用源吗？上面的备用源已经不存在了

**Comment by zjdevo** [comment]
你好，应houyunhuang本人要求，本频道不在提供该包的源
&nbsp;




------------------

 Zhou Jian
Institute of Subtropical Agriculture (ISA), 
The Chinese Academy of Science (CAS), 
University of Chinese Academy of Science(UCAS), 
Hunan, Changsha 410125, Post Box 10,P.R.China,
Phone:(+86)731-4619756, 
Fax: (+86) 4612685,
Cell phone: 15616197552，
E-mail:  zj@zlab.ac.cn;izhoujian@foxmail.com 
ORCID :0000-0002-2140-8967.





  

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Longchunyan7788"; 
Date: 2021年1月22日(星期五) 中午11:01
To: "zlabx/Microbiome"; 
Cc: "Zhoujian"; "Comment"; 
Subject: Re: [zlabx/Microbiome] ggcor 无法安装了 (#1)

&nbsp;


 
请问还有别的备用源吗？上面的备用源已经不存在了
